# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  gnutar,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "1wfhl6m0s1j80fyipcc4jwzml60c1cgzny1ggfzb74gdsgxgwzq0";
    x86_64-linux = "0blcsddkm35kg6k342a6jh6z35rqy5ghyghpyjma6nhwln1cbjxb";
    aarch64-linux = "085nrm3yrnwcik17ag81mvfpavk74s07qngs7ia2plxp06w5dz2d";
    x86_64-darwin = "0siswa266735ygqwixdy0adggfmk1cw8ziic408b285fqsf3mg4f";
    aarch64-darwin = "1jfq5j6q6k9h8z9z90qadg3ljq2ws0cvbnqy472745k9b26kn81z";
  };

  urlMap = {
    i686-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_linux_386.tar.gz";
    x86_64-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "govm";
  version = "0.0.7";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./govm $out/bin/govm
    wrapProgram $out/bin/govm --prefix PATH : ${lib.makeBinPath ([ gnutar ])}
  '';

  meta = {
    description = "Go Version Manager (govm) simplifies the management of Go installations.";
    homepage = "https://github.com/sbonaiva/govm";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
