# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  gnutar,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "01c155l9nzjbmkiqsak4h992ssp44qy5rra9mnrkxrvqdsfqlq8p";
    x86_64-linux = "0xl8wac401dhknmi5ah2d83y2mg0fdmwww7ccvpymak1a1cg1jxb";
    aarch64-linux = "1kzjv3gm0f6dg9b7mry3s47hj48xzfv3j3rba8cyxh37qi51fysc";
    x86_64-darwin = "07pgdsxc12jnx8myv08g3n12lk7sp9cvg3kzknv2906wx9ycb0jm";
    aarch64-darwin = "1j7z1sbhq7d5rz3360pvqdnz1wj5gmh0dryykhafbkb0l166vln1";
  };

  urlMap = {
    i686-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_0.0.7_linux_386.tar.gz";
    x86_64-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_0.0.7_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_0.0.7_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_0.0.7_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_0.0.7_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "govm";
  version = "0.0.7";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./govm $out/bin/govm
    wrapProgram $out/bin/govm --prefix PATH : ${lib.makeBinPath ([ gnutar ])}
  '';

  meta = {
    description = "Go Version Manager (govm) simplifies the management of Go installations.";
    homepage = "https://github.com/sbonaiva/govm";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
