# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  gnutar,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "10s2ki98rc9ckij4pnvyqs8sbfidphbx8ri5irxskkiijdag8izs";
    x86_64-linux = "02yi1fcfvhd9wlrkjr9hra816l5xr3dzb5v7hrqr5bf49mzp0zz6";
    aarch64-linux = "1464acrdg0klpp3lrj98ya8r5w7vpm7b4rmqpr195ifgd8g7i7vi";
    x86_64-darwin = "1k8492nxf4k14b3x227jfc74wdm6hirmz9la5c8zfwdc11qkvz57";
    aarch64-darwin = "1i61arhrdz5pbqkvn8kn6avdfdh8w9bhxg57ky7mazyb8zr13ixx";
  };

  urlMap = {
    i686-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_linux_386.tar.gz";
    x86_64-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/sbonaiva/govm/releases/download/v0.0.7/govm_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "govm";
  version = "0.0.7";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./govm $out/bin/govm
    wrapProgram $out/bin/govm --prefix PATH : ${lib.makeBinPath ([ gnutar ])}
  '';

  meta = {
    description = "Go Version Manager (govm) simplifies the management of Go installations.";
    homepage = "https://github.com/sbonaiva/govm";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
