# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
  gnutar,
  makeWrapper,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    i686-linux = "0xa04aiqbb8ybn3ibdcadns6jzz2y9qwcmklh984cxzk4b45mh74";
    x86_64-linux = "0v9n8a74k54lw3ml1sa9rl6bcfc73q535vghsn5i0vwm3b6fax30";
    aarch64-linux = "1f5r3ikmq7s1bv6pja4hlmadjwfa8n30p23d8ivrv8zgbd26i6bx";
    x86_64-darwin = "1p0zifj774fjd73b2w4mkkiqxywxc1y9028b4zlml8663cy8z7i1";
    aarch64-darwin = "0v3ri4nv0a6c9f2qsnk7bqvf2g345d4p89rccqvlv5c452zafqrg";
  };

  urlMap = {
    i686-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.6/govm_0.0.6_linux_386.tar.gz";
    x86_64-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.6/govm_0.0.6_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/sbonaiva/govm/releases/download/v0.0.6/govm_0.0.6_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/sbonaiva/govm/releases/download/v0.0.6/govm_0.0.6_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/sbonaiva/govm/releases/download/v0.0.6/govm_0.0.6_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "govm";
  version = "0.0.6";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles makeWrapper ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./govm $out/bin/govm
    wrapProgram $out/bin/govm --prefix PATH : ${lib.makeBinPath ([ gnutar ])}
  '';

  meta = {
    description = "Go Version Manager (govm) simplifies the management of Go installations.";
    homepage = "https://github.com/sbonaiva/govm";
    license = lib.licenses.asl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
